* **Submitted by:**
* **Lakshay Singla**
* **102003371**
* **3CO15**


**ASSIGNMENT 1**

**Q1(a): Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,6,4,5])
a = np.flipud(a)
print("The reversed array is",a)

The reversed array is [5 4 6 3 2 1]


**Q1(b)**

In [ ]:
arr = np.array([[1,2,3],[2,3,4],[1,2,3]])
print("Flatten",arr.flatten())
print("Ravel",arr.ravel())

Flatten [1 2 3 2 3 4 1 2 3]
Ravel [1 2 3 2 3 4 1 2 3]


**1(c)**

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print("Comparison:\n ",arr1==arr2)

Comparison:
  [[ True  True]
 [ True  True]]


**1(d)**

In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
List = [x,y]
for i in List:
  index = []
  count = np.bincount(i).argmax()
  print("Most freqnent elemenent ", count)
  index = [y for y in range(0,len(i)) if i[y]==count]
  print("List of indices is as: ",index)


Most freqnent elemenent  1
List of indices is as:  [0, 5, 7, 8, 9]
Most freqnent elemenent  1
List of indices is as:  [0, 1, 2]


 **1(e)**

In [ ]:
gfg = np.matrix('[4,1,0;12,3,1;4,5,6]')
print("Total: ",gfg.sum())
print("Along x:" ,gfg.sum(axis=0))
print("Along y:\n" ,gfg.sum(axis=1))

Total:  36
Along x: [[20  9  7]]
Along y:
 [[ 5]
 [16]
 [15]]


**1(f)**

In [ ]:
n = np.array([[55,25,15],
              [30,4,2],
              [11,45,77]])
print("TRACE:\n ",np.trace(n))
print("\nEigen Values:\n ",np.linalg.eig(n))
print("\nInverse Values\n ",np.linalg.inv(n))
print("Determinant: ",np.linalg.det(n))

TRACE:
  136

Eigen Values:
  (array([-5.62502721, 49.37032502, 92.25470219]), array([[-0.24809905,  0.55429855,  0.46837517],
       [ 0.86423518,  0.33288849,  0.17882043],
       [-0.43765787, -0.76284885,  0.86524445]]))

Inverse Values
  [[-0.00850898  0.04879001  0.00039032]
 [ 0.08930523 -0.15886027 -0.01327088]
 [-0.0509758   0.08587041  0.02068696]]
Determinant:  -25620.0


**1(g)**

In [ ]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print("The Multiplication is\n",np.dot(p,q))
print("The covariance is\n",np.cov(p,q))

The Multiplication is
 [[16 19]
 [26 31]]
The covariance is
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


**1(h)**

In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
innerr = np.inner(x,y)
outerr = np.outer(x,y)
crosss = np.cross(x,y)
print("Inner: \n",innerr)
print("Outer: \n",outerr)
print("Cartesian: \n",crosss)

Inner: 
 [[17 52]
 [13 62]]
Outer: 
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian: 
 [[-20   4   7]
 [-84  36  20]]


In [ ]:
'''
Submitted by:
Lakshay Singla
102003371
3CO15
'''

**Question 2**

**2(a)**

In [ ]:
abs = np.array([[1, -2, 3],[-4, 5, -6]])
absol = np.abs(abs)
absol

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
P25 = np.percentile(abs,25)
P50 = np.percentile(abs,50)
P75 = np.percentile(abs,75)
print(P25)
print(P50)
print(P75)

-3.5
-0.5
2.5


In [ ]:
#y axis
P25 = np.percentile(abs,25,axis = 0)
P50 = np.percentile(abs,50,axis = 0)
P75 = np.percentile(abs,75,axis = 0)
print(P25)
print(P50)
print(P75)

[-2.75 -0.25 -3.75]
[-1.5  1.5 -1.5]
[-0.25  3.25  0.75]


In [ ]:
#x axis
P25 = np.percentile(abs,25,axis = 1)
P50 = np.percentile(abs,50,axis = 1)
P75 = np.percentile(abs,75,axis = 1)
print(P25)
print(P50)
print(P75)

[-0.5 -5. ]
[ 1. -4.]
[2.  0.5]


In [ ]:
mean = np.mean(abs)
median = np.median(abs)
std = np.std(abs)
print("Median: ",median)
print("Mean: ",mean)
print("STD: ",std)

Median:  -0.5
Mean:  -0.5
STD:  3.8622100754188224


In [ ]:
for i in range(0,2):
  print("ALONG AXIS: ",i)
  axis = i
  mean = np.mean(abs,axis = axis)
  median = np.median(abs,axis = axis)
  std = np.std(abs,axis = axis)
  print("Median: ",median)
  print("Mean: ",mean)
  print("STD: ",std)

ALONG AXIS:  0
Median:  [-1.5  1.5 -1.5]
Mean:  [-1.5  1.5 -1.5]
STD:  [2.5 3.5 4.5]
ALONG AXIS:  1
Median:  [ 1. -4.]
Mean:  [ 0.66666667 -1.66666667]
STD:  [2.05480467 4.78423336]


**2(B)**

In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
floor = np.floor(a)
ceil  = np.ceil(a)
truncate = np.trunc(a)
round = np.round(a)
print("Floor: ",floor)
print("Ceil: ",ceil)
print("Truncate :",truncate)
print("Round: ",round)

Floor:  [-2. -2. -1.  0.  1.  1.  3.]
Ceil:  [-1. -1. -0.  1.  2.  2.  3.]
Truncate : [-1. -1. -0.  0.  1.  1.  3.]
Round:  [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
'''
Submitted by:
Lakshay Singla
102003371
3CO15
'''

**Question 3**

**3(a)**

In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted = np.sort(array)
argsort = np.argsort(array)
print("Sorted array: ",sorted)
print("Indices: ",argsort)
x = [i for i in sorted]
print("SMALLEST: ",x[:4])
x = [i for i in sorted]
print("LARGEST: ",x[-5:])

Sorted array:  [ 10  16  16  52  54  62 453]
Indices:  [0 3 4 1 5 2 6]
SMALLEST:  [10, 16, 16, 52]
LARGEST:  [16, 52, 54, 62, 453]


**3(B)**

In [ ]:
import math as m
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
floating = [x for x in array if x==m.floor(x)]
integer = [x for x in array if x!=m.floor(x)]
print(integer)
print(floating)

[1.2, 2.2]
[1.0, 2.0, 3.0, 2.0]


In [ ]:
'''
Submitted by:
Lakshay Singla
102003371
3CO15
'''

**Question 4**

In [ ]:
import cv2
from google.colab import files

In [ ]:
def img_to_array(path="test.jpg"):
      choice= int(input("Enter 0 for grayscale and 1 for RGB: "))
      img= cv2.imread(path,choice)
      file = open("myfile.txt","w")
      file.write(str(img))
      file.close()
      files.download("myfile.txt")

In [ ]:
img_to_array('/content/Lakshay.jpg')

**Submitted by Lakshay Singla**
