**ML ASSIGNMENT 3**

*   **Lakshay Singla**
*   **102003371**
*   **3CO15**



**Importing Libraries**

In [ ]:
import numpy as np
import pandas as pd

**Merging the two given datasets**

In [ ]:
df = pd.read_csv('AWCustomers.csv')
extra = pd.read_csv('AWSales.csv')
df = pd.merge(df,extra)
df.head()

CustomerID Title FirstName MiddleName  LastName Suffix  \
0       21173   NaN      Chad          C      Yuan    NaN   
1       13249   NaN      Ryan        NaN     Perry    NaN   
2       29350   NaN     Julia        NaN  Thompson    NaN   
3       13503   NaN  Theodore        NaN     Gomez    NaN   
4       22803   NaN  Marshall          J      Shan    NaN   

             AddressLine1 AddressLine2         City    StateProvinceName  ...  \
0      7090 C. Mount Hood          NaN   Wollongong      New South Wales  ...   
1     3651 Willow Lake Rd          NaN      Shawnee     British Columbia  ...   
2  1774 Tice Valley Blvd.          NaN  West Covina           California  ...   
3         2103 Baldwin Dr          NaN    Liverpool              England  ...   
4         Am Gallberg 234          NaN        Werne  Nordrhein-Westfalen  ...   

  Gender MaritalStatus HomeOwnerFlag NumberCarsOwned NumberChildrenAtHome  \
0      M             M             1               3                    0   
1      M             M             1               2                    1   
2      F             S             0               3                    0   
3      M             M             1               2                    1   
4      M             S             1               1                    0   

  TotalChildren YearlyIncome LastUpdated  BikeBuyer  AvgMonthSpend  
0             1        81916  2017-03-06          1          50.97  
1             2        81076  2017-03-06          1          53.11  
2             0        86387  2017-03-06          1          54.08  
3             2        61481  2017-03-06          1          56.93  
4             0        51804  2017-03-06          1          55.41  

[5 rows x 26 columns]

**Dropping duplicate ids present if any**

In [ ]:
df = df.drop_duplicates(subset=['CustomerID'])

**Removing the extra columns**

In [ ]:
df = df.drop(['CustomerID','Title','FirstName','MiddleName','LastName','Suffix','AddressLine1','AddressLine2','PostalCode','PhoneNumber','LastUpdated','City','StateProvinceName'],axis = 1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18355 entries, 0 to 18360
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   CountryRegionName     18355 non-null  object 
 1   BirthDate             18355 non-null  object 
 2   Education             18355 non-null  object 
 3   Occupation            18355 non-null  object 
 4   Gender                18355 non-null  object 
 5   MaritalStatus         18355 non-null  object 
 6   HomeOwnerFlag         18355 non-null  int64  
 7   NumberCarsOwned       18355 non-null  int64  
 8   NumberChildrenAtHome  18355 non-null  int64  
 9   TotalChildren         18355 non-null  int64  
 10  YearlyIncome          18355 non-null  int64  
 11  BikeBuyer             18355 non-null  int64  
 12  AvgMonthSpend         18355 non-null  float64
dtypes: float64(1), int64(6), object(6)
memory usage: 2.0+ MB


In [ ]:
df.head()

CountryRegionName   BirthDate        Education      Occupation Gender  \
0         Australia  1987-11-13        Bachelors        Clerical      M   
1            Canada  1972-07-21  Partial College        Clerical      M   
2     United States  1985-11-09        Bachelors        Clerical      F   
3    United Kingdom  1977-10-18  Partial College  Skilled Manual      M   
4           Germany  1975-02-05  Partial College  Skilled Manual      M   

  MaritalStatus  HomeOwnerFlag  NumberCarsOwned  NumberChildrenAtHome  \
0             M              1                3                     0   
1             M              1                2                     1   
2             S              0                3                     0   
3             M              1                2                     1   
4             S              1                1                     0   

   TotalChildren  YearlyIncome  BikeBuyer  AvgMonthSpend  
0              1         81916          1          50.97  
1              2         81076          1          53.11  
2              0         86387          1          54.08  
3              2         61481          1          56.93  
4              0         51804          1          55.41

**Calculating Age from DOB**

In [ ]:
from datetime import datetime
from datetime import date
def calculate_age(born):
    born = datetime.strptime(born, "%Y-%m-%d").date()
    today = date.today()
    return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

df['age'] = df['BirthDate'].apply(calculate_age)
df = df.drop('BirthDate',axis = 1)
df.head()

CountryRegionName        Education      Occupation Gender MaritalStatus  \
0         Australia        Bachelors        Clerical      M             M   
1            Canada  Partial College        Clerical      M             M   
2     United States        Bachelors        Clerical      F             S   
3    United Kingdom  Partial College  Skilled Manual      M             M   
4           Germany  Partial College  Skilled Manual      M             S   

   HomeOwnerFlag  NumberCarsOwned  NumberChildrenAtHome  TotalChildren  \
0              1                3                     0              1   
1              1                2                     1              2   
2              0                3                     0              0   
3              1                2                     1              2   
4              1                1                     0              0   

   YearlyIncome  BikeBuyer  AvgMonthSpend  age  
0         81916          1          50.97   34  
1         81076          1          53.11   50  
2         86387          1          54.08   36  
3         61481          1          56.93   44  
4         51804          1          55.41   47

**Checking for NULL values**

In [ ]:
df.isnull().sum()

CountryRegionName       0
Education               0
Occupation              0
Gender                  0
MaritalStatus           0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            0
BikeBuyer               0
AvgMonthSpend           0
age                     0
dtype: int64

**Converting into numerical form for further processing**

*   **One Hot Encoding**




In [ ]:
Genderr = pd.get_dummies(df.Gender)
Genderr = Genderr.drop('F',axis = 1)
df = pd.concat([df,Genderr],axis = 'columns')
df = df.drop('Gender',axis = 'columns')
df.rename(columns = {'M':'Male'},inplace = True)
df.head()

CountryRegionName        Education      Occupation MaritalStatus  \
0         Australia        Bachelors        Clerical             M   
1            Canada  Partial College        Clerical             M   
2     United States        Bachelors        Clerical             S   
3    United Kingdom  Partial College  Skilled Manual             M   
4           Germany  Partial College  Skilled Manual             S   

   HomeOwnerFlag  NumberCarsOwned  NumberChildrenAtHome  TotalChildren  \
0              1                3                     0              1   
1              1                2                     1              2   
2              0                3                     0              0   
3              1                2                     1              2   
4              1                1                     0              0   

   YearlyIncome  BikeBuyer  AvgMonthSpend  age  Male  
0         81916          1          50.97   34     1  
1         81076          1          53.11   50     1  
2         86387          1          54.08   36     0  
3         61481          1          56.93   44     1  
4         51804          1          55.41   47     1

In [ ]:
Status = pd.get_dummies(df.MaritalStatus,drop_first=True)
df = pd.concat([df,Status],axis = 'columns')
df = df.drop('MaritalStatus',axis = 1)
df.head()

CountryRegionName        Education      Occupation  HomeOwnerFlag  \
0         Australia        Bachelors        Clerical              1   
1            Canada  Partial College        Clerical              1   
2     United States        Bachelors        Clerical              0   
3    United Kingdom  Partial College  Skilled Manual              1   
4           Germany  Partial College  Skilled Manual              1   

   NumberCarsOwned  NumberChildrenAtHome  TotalChildren  YearlyIncome  \
0                3                     0              1         81916   
1                2                     1              2         81076   
2                3                     0              0         86387   
3                2                     1              2         61481   
4                1                     0              0         51804   

   BikeBuyer  AvgMonthSpend  age  Male  S  
0          1          50.97   34     1  0  
1          1          53.11   50     1  0  
2          1          54.08   36     0  1  
3          1          56.93   44     1  0  
4          1          55.41   47     1  1

**Mapping the Education with labels More the education More is the weightage Similar with Occupation**

In [ ]:
df['Occupation']=df['Occupation'].map({'Manual':1,'Skilled Manual':2,'Clerical':3,'Management':4,'Professional':5})
df['Education']=df['Education'].map({'Partial High School':1,'High School':2,'Partial College':3,'Bachelors':4,'Graduate Degree':5})
df.head()

CountryRegionName  Education  Occupation  HomeOwnerFlag  NumberCarsOwned  \
0         Australia          4           3              1                3   
1            Canada          3           3              1                2   
2     United States          4           3              0                3   
3    United Kingdom          3           2              1                2   
4           Germany          3           2              1                1   

   NumberChildrenAtHome  TotalChildren  YearlyIncome  BikeBuyer  \
0                     0              1         81916          1   
1                     1              2         81076          1   
2                     0              0         86387          1   
3                     1              2         61481          1   
4                     0              0         51804          1   

   AvgMonthSpend  age  Male  S  
0          50.97   34     1  0  
1          53.11   50     1  0  
2          54.08   36     0  1  
3          56.93   44     1  0  
4          55.41   47     1  1

**PERFORMING ONE HOT ENCODING**

In [ ]:
CountryRegionName = pd.get_dummies(df.CountryRegionName,drop_first=True)
df = pd.concat([df,CountryRegionName],axis = 'columns')
df = df.drop('CountryRegionName',axis = 1)
df.head()

Education  Occupation  HomeOwnerFlag  NumberCarsOwned  \
0          4           3              1                3   
1          3           3              1                2   
2          4           3              0                3   
3          3           2              1                2   
4          3           2              1                1   

   NumberChildrenAtHome  TotalChildren  YearlyIncome  BikeBuyer  \
0                     0              1         81916          1   
1                     1              2         81076          1   
2                     0              0         86387          1   
3                     1              2         61481          1   
4                     0              0         51804          1   

   AvgMonthSpend  age  Male  S  Canada  France  Germany  United Kingdom  \
0          50.97   34     1  0       0       0        0               0   
1          53.11   50     1  0       1       0        0               0   
2          54.08   36     0  1       0       0        0               0   
3          56.93   44     1  0       0       0        0               1   
4          55.41   47     1  1       0       0        1               0   

   United States  
0              0  
1              0  
2              1  
3              0  
4              0

In [ ]:
df['4 bins'] = pd.qcut(df['age'], q=4)
df.head()

Education  Occupation  HomeOwnerFlag  NumberCarsOwned  \
0          4           3              1                3   
1          3           3              1                2   
2          4           3              0                3   
3          3           2              1                2   
4          3           2              1                1   

   NumberChildrenAtHome  TotalChildren  YearlyIncome  BikeBuyer  \
0                     0              1         81916          1   
1                     1              2         81076          1   
2                     0              0         86387          1   
3                     1              2         61481          1   
4                     0              0         51804          1   

   AvgMonthSpend  age  Male  S  Canada  France  Germany  United Kingdom  \
0          50.97   34     1  0       0       0        0               0   
1          53.11   50     1  0       1       0        0               0   
2          54.08   36     0  1       0       0        0               0   
3          56.93   44     1  0       0       0        0               1   
4          55.41   47     1  1       0       0        1               0   

   United States        4 bins  
0              0  (31.0, 39.0]  
1              0  (47.0, 92.0]  
2              1  (31.0, 39.0]  
3              0  (39.0, 47.0]  
4              0  (39.0, 47.0]

**SCALING AND NORMALIZING THE DATA**

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaled=scaler.fit_transform(df[['YearlyIncome','age','AvgMonthSpend']])
df['YearlyIncome_scaled']=scaled[:,0]
df['Age_scaled']=scaled[:,1]
df['AvgMonthSpend_Scaled']=scaled[:,2]
df.drop(['YearlyIncome','age'],axis=1,inplace=True)
df = df.drop('AvgMonthSpend',axis=1)
df.head()

Education  Occupation  HomeOwnerFlag  NumberCarsOwned  \
0              4           3              1                3   
1              3           3              1                2   
2              4           3              0                3   
3              3           2              1                2   
4              3           2              1                1   
...          ...         ...            ...              ...   
18356          5           2              0                1   
18357          4           2              0                2   
18358          3           2              0                2   
18359          2           3              0                0   
18360          5           5              1                2   

       NumberChildrenAtHome  TotalChildren  BikeBuyer  Male  S  Canada  \
0                         0              1          1     1  0       0   
1                         1              2          1     1  0       1   
2                         0              0          1     0  1       0   
3                         1              2          1     1  0       0   
4                         0              0          1     1  1       0   
...                     ...            ...        ...   ... ..     ...   
18356                     0              2          0     0  0       0   
18357                     0              0          1     0  1       0   
18358                     0              0          1     0  1       0   
18359                     0              0          0     0  1       1   
18360                     0              0          1     0  0       0   

       France  Germany  United Kingdom  United States          4 bins  \
0           0        0               0              0    (31.0, 39.0]   
1           0        0               0              0    (47.0, 92.0]   
2           0        0               0              1    (31.0, 39.0]   
3           0        0               1              0    (39.0, 47.0]   
4           0        1               0              0    (39.0, 47.0]   
...       ...      ...             ...            ...             ...   
18356       0        0               0              1  (20.999, 31.0]   
18357       0        0               0              0  (20.999, 31.0]   
18358       0        0               0              1    (31.0, 39.0]   
18359       0        0               0              0  (20.999, 31.0]   
18360       0        0               0              1    (31.0, 39.0]   

       YearlyIncome_scaled  Age_scaled  AvgMonthSpend_Scaled  
0                 0.496842    0.183099              0.324210  
1                 0.489453    0.408451              0.425201  
2                 0.536172    0.211268              0.470977  
3                 0.317083    0.323944              0.605474  
4                 0.231958    0.366197              0.533742  
...                    ...         ...                   ...  
18356             0.242065    0.140845              0.190656  
18357             0.312781    0.112676              0.289287  
18358             0.232442    0.239437              0.257669  
18359             0.543121    0.084507              0.345446  
18360             0.980128    0.211268              0.385559  

[18355 rows x 18 columns]

**COSINE**

In [ ]:
from numpy.linalg import norm
A = df['YearlyIncome_scaled']
B = df['Education']
cosine = np.dot(A,B)/(norm(A)*norm(B))
print("Cosine Similarity between YearlyIncome_Scaled and Education", cosine)

Cosine Similarity between YearlyIncome_Scaled and Education 0.87552000634723


In [ ]:
from scipy.spatial import distance
distance.cosine(df['Education'].values,df['YearlyIncome_scaled'].values)
distance.cosine(df['Education'].values,df['AvgMonthSpend_Scaled'].values)
distance.cosine(df['TotalChildren'].values,df['BikeBuyer'].values)

0.39451704519752906

**JACCARD SCORE**

In [ ]:
from sklearn.metrics import jaccard_score
print(jaccard_score(df['Canada'], df['Male']))
print(jaccard_score(df['Germany'], df['Male']))

0.07924340467894475
0.08854525755934206


**PEARSON CORRELATION**

In [ ]:
print(np.corrcoef(df['Education'], df['YearlyIncome_scaled']))
print(np.corrcoef(df['BikeBuyer'], df['TotalChildren']))
print(np.corrcoef(df['BikeBuyer'], df['Age_scaled']))
print(np.corrcoef(df['Age_scaled'], df['TotalChildren']))

[[1.         0.46768437]
 [0.46768437 1.        ]]
[[1.         0.20962836]
 [0.20962836 1.        ]]
[[1.         0.09735391]
 [0.09735391 1.        ]]
[[1.         0.54791876]
 [0.54791876 1.        ]]


 --------------------**SUBMITTED BY LAKSHAY SINGLA** --------------------           