
```
Lakshay Singla
102003371
3CO15

Submission of ASSIGNMENT 6
```



# **ASSIGNMENT_6_LOGISTIC_REGRESSION**

In [ ]:
import pandas as pd
import matplotlib.pyplot as py
import numpy as np

### **QUESTION 1**

In [ ]:
from sklearn import datasets
from sklearn.preprocessing import MinMaxScaler
iris = datasets.load_iris() 
df = pd.DataFrame(iris.data)
df['target'] = iris.target

In [ ]:
df.head()

0    1    2    3  target
0  5.1  3.5  1.4  0.2       0
1  4.9  3.0  1.4  0.2       0
2  4.7  3.2  1.3  0.2       0
3  4.6  3.1  1.5  0.2       0
4  5.0  3.6  1.4  0.2       0

In [ ]:
from sklearn.model_selection import train_test_split
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=3)

trainer = MinMaxScaler()
trainer = trainer.fit_transform(x_train,y_train)

tester = MinMaxScaler()
tester = tester.fit_transform(x_test,y_test)

In [ ]:
trainer.shape

(120, 4)

In [ ]:
df_train = pd.DataFrame(df)
df_train.columns=['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid','target']
df_train.head()

sepal_len  sepal_wid  petal_len  petal_wid  target
0        5.1        3.5        1.4        0.2       0
1        4.9        3.0        1.4        0.2       0
2        4.7        3.2        1.3        0.2       0
3        4.6        3.1        1.5        0.2       0
4        5.0        3.6        1.4        0.2       0

In [ ]:
df.insert(0, "ones", 1, True)
n = df.shape[0]
alpha = 0.01

In [ ]:
df1 = df.copy()
df2 = df.copy()
df3 = df.copy()

In [ ]:
def ConvertToBinary(df,ind):
  df.is_copy = False
  for i in range(0,n):
    if df.iloc[i,5] == ind:
      df.iloc[i,5]  = 1 
    elif df.iloc[i,5] != ind:
      df.iloc[i,5]  = 0
  print(df)
  return df

In [ ]:
df1=ConvertToBinary(df1,0)
df2=ConvertToBinary(df2,1)
df3=ConvertToBinary(df3,2)

     ones  sepal_len  sepal_wid  petal_len  petal_wid  target
0       1        5.1        3.5        1.4        0.2       1
1       1        4.9        3.0        1.4        0.2       1
2       1        4.7        3.2        1.3        0.2       1
3       1        4.6        3.1        1.5        0.2       1
4       1        5.0        3.6        1.4        0.2       1
..    ...        ...        ...        ...        ...     ...
145     1        6.7        3.0        5.2        2.3       0
146     1        6.3        2.5        5.0        1.9       0
147     1        6.5        3.0        5.2        2.0       0
148     1        6.2        3.4        5.4        2.3       0
149     1        5.9        3.0        5.1        1.8       0

[150 rows x 6 columns]
     ones  sepal_len  sepal_wid  petal_len  petal_wid  target
0       1        5.1        3.5        1.4        0.2       0
1       1        4.9        3.0        1.4        0.2       0
2       1        4.7        3.2        1.3    

**REAL CODE STARTS HERE**

In [ ]:
beta_count = df.shape[1]-1
beta1 = np.zeros(beta_count)
beta2 = np.zeros(beta_count)
beta3 = np.zeros(beta_count)

In [ ]:
def findBetas(df,beta):
  x = df.iloc[:,:-1]
  y = df.iloc[:,-1]
  for iteration in range(5000):
    print(iteration)
    z = np.dot(x,beta)
    for j in range(beta_count):
      t_dJ=0
      for i in range(n):
        hypo = 1/(1+np.exp(-z[i]))
        dJ = (hypo - y[i])*x.iloc[i,j]
        t_dJ+=dJ
      beta[j]-=(alpha/n)*t_dJ 
  return beta

In [ ]:
beta1 =findBetas(df1,beta1)
beta2 =findBetas(df2,beta2)
beta3 =findBetas(df3,beta3)

In [ ]:
print(beta1)
print(beta2)
print(beta3)

[ 0.28693488  0.45010713  1.53318488 -2.40404209 -1.08580724]
[ 0.4074006   0.40638772 -1.34346969  0.42800077 -0.94167673]
[-0.80469168 -1.57367763 -1.4148281   2.33322675  2.01157281]


In [ ]:
def findProb(df,beta):
  x = df.iloc[:,:-1]
  z = np.dot(x,beta)
  fx = 1/(1+np.exp(-z))
  for i in range(n):
    if fx[i]<0.5:
      fx[i]=0
  return fx

In [ ]:
p1=findProb(df1,beta1)
p2=findProb(df2,beta2)
p3=findProb(df3,beta3)

In [ ]:
p2[0]

0.0

In [ ]:
p1[3]

0.9639827781628152

In [ ]:
y_predict = np.zeros(n)
for i in range(n):
  if p1[i]>=p2[i] and p1[i]>=p3[i]:
    y_predict[i] = 0
  elif (p2[i]>=p3[i] and p2[i]>=p1[i]):
    y_predict[i] = 1
  else:
    y_predict[i] = 2

In [ ]:
def findAccuracy(x,y):
  count = 0
  for i in range(n):
    if(x[i]==y[i]):
      count+=1
  accuracy = (count/n)*100
  print(accuracy)

In [ ]:
findAccuracy(y,y_predict)

76.0


## **Question 2**

### ***`Question`*** 2(i)


In [ ]:
exam = pd.read_csv('exam6.txt',header = None)
exam.head(2)

0        1  2
0  0.051267  0.69956  1
1 -0.092742  0.68494  1

In [ ]:
exam.head(2)

0        1  2
0  0.051267  0.69956  1
1 -0.092742  0.68494  1

In [ ]:
exam.drop(['x1_2'],axis=1,inplace = True)
exam

0         1  2
0    0.051267  0.699560  1
1   -0.092742  0.684940  1
2   -0.213710  0.692250  1
3   -0.375000  0.502190  1
4   -0.513250  0.465640  1
..        ...       ... ..
113 -0.720620  0.538740  0
114 -0.593890  0.494880  0
115 -0.484450  0.999270  0
116 -0.006336  0.999270  0
117  0.632650 -0.030612  0

[118 rows x 3 columns]

In [ ]:
# exam.drop(['x1_3','x11_3','x111_3'],axis = 1,inplace = True)
exam

ones         0         1      x1_2      x2_2      x2_3  2
0       1  0.051267  0.699560  0.002628  0.489384  0.342354  1
1       1 -0.092742  0.684940  0.008601  0.469143  0.321335  1
2       1 -0.213710  0.692250  0.045672  0.479210  0.331733  1
3       1 -0.375000  0.502190  0.140625  0.252195  0.126650  1
4       1 -0.513250  0.465640  0.263426  0.216821  0.100960  1
..    ...       ...       ...       ...       ...       ... ..
113     1 -0.720620  0.538740  0.519293  0.290241  0.156364  0
114     1 -0.593890  0.494880  0.352705  0.244906  0.121199  0
115     1 -0.484450  0.999270  0.234692  0.998541  0.997812  0
116     1 -0.006336  0.999270  0.000040  0.998541  0.997812  0
117     1  0.632650 -0.030612  0.400246  0.000937 -0.000029  0

[118 rows x 7 columns]

In [ ]:
exam.insert(exam.shape[1]-1,"x1_2",exam[0]**2)
exam.insert(exam.shape[1]-1,"x2_2",exam[1]**2)
exam.insert(exam.shape[1]-1,"x2_3",exam[1]**3)
exam.insert(exam.shape[1]-1,"x1_3",exam[0]**3)
exam.insert(exam.shape[1]-1,"x1_4",exam[0]**4)
exam.insert(exam.shape[1]-1,"x2_4",exam[1]**4)
exam.insert(0,"ones",1,True)
exam

ones         0         1      x1_2      x2_2      x2_3          x1_3  \
0       1  0.051267  0.699560  0.002628  0.489384  0.342354  1.347453e-04   
1       1 -0.092742  0.684940  0.008601  0.469143  0.321335 -7.976812e-04   
2       1 -0.213710  0.692250  0.045672  0.479210  0.331733 -9.760555e-03   
3       1 -0.375000  0.502190  0.140625  0.252195  0.126650 -5.273438e-02   
4       1 -0.513250  0.465640  0.263426  0.216821  0.100960 -1.352032e-01   
..    ...       ...       ...       ...       ...       ...           ...   
113     1 -0.720620  0.538740  0.519293  0.290241  0.156364 -3.742131e-01   
114     1 -0.593890  0.494880  0.352705  0.244906  0.121199 -2.094682e-01   
115     1 -0.484450  0.999270  0.234692  0.998541  0.997812 -1.136964e-01   
116     1 -0.006336  0.999270  0.000040  0.998541  0.997812 -2.544062e-07   
117     1  0.632650 -0.030612  0.400246  0.000937 -0.000029  2.532156e-01   

             x1_4          x2_4  2  
0    6.907989e-06  2.394969e-01  1  
1    7.397855e-05  2.200950e-01  1  
2    2.085928e-03  2.296423e-01  1  
3    1.977539e-02  6.360222e-02  1  
4    6.939303e-02  4.701118e-02  1  
..            ...           ... ..  
113  2.696654e-01  8.423971e-02  0  
114  1.244011e-01  5.997905e-02  0  
115  5.508024e-02  9.970832e-01  0  
116  1.612020e-09  9.970832e-01  0  
117  1.601969e-01  8.781462e-07  0  

[118 rows x 10 columns]

In [ ]:
n = exam.shape[0]
alpha = 10
beta_count = exam.shape[1]
beta = np.zeros(beta_count-1)

In [ ]:
def findBetas(df,beta):
  x = df.iloc[:,:-1]
  y = df.iloc[:,-1]
  for iteration in range(1000):
    print(iteration)
    z = np.dot(x,beta)
    for j in range(beta_count-1):
      t_dJ=0
      for i in range(n):
        hypo = 1/(1+np.exp(-z[i]))
        dJ = (hypo - y[i])*x.iloc[i,j]
        t_dJ+=dJ
      beta[j]-=(alpha/n)*t_dJ 
  return beta

In [ ]:
beta = findBetas(exam,beta)

In [ ]:
beta

array([ 3.12240582,  0.50691247,  3.08012648, -3.43596764, -5.58370252,
       -2.4152913 ,  2.72967317, -9.11691845, -1.16760715])

In [ ]:
def findProb(df,beta):
  x = df.iloc[:,:-1]
  z = np.dot(x,beta)
  fx = 1/(1+np.exp(-z))
  for i in range(n):
    if fx[i]<0.5:
      fx[i]=0
    else: fx[i]=1
  return fx

In [ ]:
p = findProb(exam,beta)
p

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [ ]:
exam.iloc[:,-1]

0      1
1      1
2      1
3      1
4      1
      ..
113    0
114    0
115    0
116    0
117    0
Name: 2, Length: 118, dtype: int64

In [ ]:
def findAccuracy(x,y):
  count = 0
  for i in range(n):
    if(x[i]==y[i]):
      count+=1
  accuracy = (count/n)*100
  print(accuracy)

In [ ]:
findAccuracy(exam.iloc[:,-1],p)

80.50847457627118


In [ ]:
# x1_2 = 56%
# & x2_2 = 80.5%
# x11_3 =x2_3  = 78%
# x1_3 = 78%


### ***`QUESTION 2(ii)`***

In [ ]:
exam

ones         0         1      x1_2      x2_2      x2_3          x1_3  \
0       1  0.051267  0.699560  0.002628  0.489384  0.342354  1.347453e-04   
1       1 -0.092742  0.684940  0.008601  0.469143  0.321335 -7.976812e-04   
2       1 -0.213710  0.692250  0.045672  0.479210  0.331733 -9.760555e-03   
3       1 -0.375000  0.502190  0.140625  0.252195  0.126650 -5.273438e-02   
4       1 -0.513250  0.465640  0.263426  0.216821  0.100960 -1.352032e-01   
..    ...       ...       ...       ...       ...       ...           ...   
113     1 -0.720620  0.538740  0.519293  0.290241  0.156364 -3.742131e-01   
114     1 -0.593890  0.494880  0.352705  0.244906  0.121199 -2.094682e-01   
115     1 -0.484450  0.999270  0.234692  0.998541  0.997812 -1.136964e-01   
116     1 -0.006336  0.999270  0.000040  0.998541  0.997812 -2.544062e-07   
117     1  0.632650 -0.030612  0.400246  0.000937 -0.000029  2.532156e-01   

             x1_4          x2_4  2  
0    6.907989e-06  2.394969e-01  1  
1    7.397855e-05  2.200950e-01  1  
2    2.085928e-03  2.296423e-01  1  
3    1.977539e-02  6.360222e-02  1  
4    6.939303e-02  4.701118e-02  1  
..            ...           ... ..  
113  2.696654e-01  8.423971e-02  0  
114  1.244011e-01  5.997905e-02  0  
115  5.508024e-02  9.970832e-01  0  
116  1.612020e-09  9.970832e-01  0  
117  1.601969e-01  8.781462e-07  0  

[118 rows x 10 columns]

In [ ]:
n = exam.shape[0]
lam = 0.2
alpha = 10
beta_count = exam.shape[1]
beta = np.zeros(beta_count-1)

In [ ]:
def findBetas(df,beta):
  x = df.iloc[:,:-1]
  y = df.iloc[:,-1]
  for iteration in range(1000):
    print(iteration)
    z = np.dot(x,beta)
    for j in range(beta_count-1):
      t_dJ=0
      for i in range(n):
        hypo = 1/(1+np.exp(-z[i]))
        dJ = (hypo - y[i])*x.iloc[i,j]+(lam/n)*beta[j]
        t_dJ+=dJ
      beta[j]-=(alpha/n)*t_dJ 
  return beta

In [ ]:
beta = findBetas(exam,beta)
beta

In [ ]:
beta

array([ 2.98680855,  0.83247894,  2.15600326, -3.93892338, -2.83407251,
       -0.89673653,  0.34134519, -3.35978371, -2.69929316])

In [ ]:
p = findProb(exam,beta)
findAccuracy(exam.iloc[:,-1],p)

77.11864406779661
